email_filter/urls.py
from django.urls import path
from .views import *



app_name = 'email_filter'
urlpatterns = [
    path('', Index.as_view(), name='index'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('products_api.urls')),
    path('admin/', admin.site.urls),
    path('', include('email_filter.urls')),
]

products_api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url('', include(router.urls)),
    url('payload', payload),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

email_filter/models.py
from django.db import models

# Create your models here.

products_api/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=30, blank= False)
    created_date = models.DateTimeField()


class DialogFlowRequest(models.Model):
    created_date = models.DateTimeField(auto_now_add=True, blank=False)
    content = models.TextField()

email_filter/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .machine_learning import SpamModel


# Create your views here.
class Index(View):
    template_name = 'index.html'

    def get(self, request):
        return render(request,self.template_name)

    def post(self, request):
        msg = request.POST['email-content']
        ml_model = SpamModel()
        prediction = ml_model.predict(msg)
        not_spam, spam = prediction[0], prediction[1]
        context = {'spam': spam, "not_spam": not_spam, 'message': msg}
        return render(request, self.template_name, context=context)

products_api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .serializer import *
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status


# Create your views here.
class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


@api_view(['POST', 'GET'])
def payload(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'POST':

        data = request.data
        d = DialogFlowRequest(content=data)
        d.save()
        try:
            if request.data["queryResult"]["intent"]["displayName"] == 'GetProducts':
                products = Product.objects.all()
                text_response = 'We have the products: '
                if len(products):
                    for product in products:
                        text_response += product.name + ','
                    text_response += ' avaiable for buying'
                else:
                    text_response = 'We have no products avaiable now, sorry!'
                df_response = {"fulfillmentMessages": [{"text": {"text" : [text_response]}}]}
                return Response(data=df_response, status=status.HTTP_200_OK,
                                content_type="application/json; charset=UTF-8")
        except KeyError:
            pass
        return Response(status=status.HTTP_200_OK)

    if request.method == 'GET':
        d_requests = DialogFlowRequest.objects.all().order_by('-created_date')
        serializer = DialogFlowRequestSerializer(d_requests, many=True)
        return Response(serializer.data)

    return Response(status=status.HTTP_400_BAD_REQUEST)

email_filter/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NLP Demos</title>
</head>
<body>
{% block 'content' %} {% endblock %}
</body>
</html>

email_filter/templates/index.html
{% extends 'base.html' %}
{% block 'content' %}

    <h2>Email Spam Detection model</h2>
    <p>This is a spam detection prototype made for personal practice and for unosquare's meetup of 18 of december of 2018</p>

    <form action="{% url 'email_filter:index' %}" method="post">
        {% csrf_token %}
        <label for="email-content">Paste here your email's content:</label>
        <br/>
        <textarea name="email-content" rows="20" style="resize:none;" cols="100" id="email-content"></textarea>
        <br/>
        <input type="submit" value="Submit">

    </form>
    {% if spam %}
        <h2>Results</h2>
        <div>For your message:</div>
        <div>{{message}}</div>
        <h4>The model concluded that is {{spam}}% that it is spam</h4>
        <h4>The model concluded that is {{not_spam}}% that it is not spam</h4>
    {% endif %}

    <iframe
        allow="microphone;"
        width="350"
        height="430"
        src="https://console.dialogflow.com/api-client/demo/embedded/e84677d8-cc78-4e60-88af-bd17271ee16b">
    </iframe>

{% endblock %}